## First Time Build
#build:
#  stage: build
#  script:
#    - echo 'Creating directory'
#    - sudo mkdir -p /var/www/html/php7.3/b-homefix
#    - cd /var/www/html/php7.3/b-homefix/
#    - echo 'Creating log files'
#    - sudo touch error.log access.log
#    - echo 'Deleting old data'
#    - sudo rm -rf b-homefix/  || true
#    - git clone git@169.45.148.195:khalid/homefix.git b-homefix
#    - sudo chmod 777 . -R
#    - sudo ls -la b-homefix/
#    - sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#    - sudo php composer-setup.php --install-dir=/bin --filename=composer
#    - sudo composer install -d b-homefix/
#    - sudo cp b-homefix/.env.example b-homefix/.env
#    - sudo docker cp b-homefix/b-homefix.conf php73_apache:/etc/apache2/sites-available/
#    - sudo docker exec php73_apache a2ensite b-homefix
#    - sudo docker exec php73_apache apachectl configtest
#    - sudo docker exec php73_apache service apache2 reload

# Don't delete anything!
build:
  stage: build
  script:
    - echo 'Creating directory'
    - sudo mkdir -p /var/www/html/php7.3/b-homefix
    - cd /var/www/html/php7.3/b-homefix/
    - echo 'Creating log files'
    - sudo touch error.log access.log
    - sudo cd /var/www/html/php7.3/b-homefix/
    - sudo ls -la /var/www/html/php7.3/b-homefix/b-homefix/
    # Pull
    - cd /var/www/html/php7.3/b-homefix/b-homefix/
    - sudo git fetch origin
    - sudo git reset --hard origin/master
    - sudo git pull --force
    - sudo chmod 777 . -R
    # Composer Install
    - cd /var/www/html/php7.3/b-homefix/
    - sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - sudo php composer-setup.php --install-dir=/bin --filename=composer
    - sudo composer install -d b-homefix/
    - sudo cp b-homefix/.env.example b-homefix/.env
    # Clear Cache
    - php b-homefix/artisan config:clear
    - php b-homefix/artisan route:clear
    - php b-homefix/artisan cache:clear
    - php b-homefix/artisan view:clear
    - sudo chmod 777 b-homefix/ -R
    - sudo docker cp b-homefix/b-homefix.conf php73_apache:/etc/apache2/sites-available/
    - sudo docker exec php73_apache a2ensite b-homefix
    - sudo docker exec php73_apache apachectl configtest
    - sudo docker exec php73_apache service apache2 reload
